version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source"
    schedule:
      interval: "daily"
    target-branch: "develop"
    ignore:
      - dependency-name: "Cake.Core"
      - dependency-name: "Cake.Common"
      - dependency-name: "Cake.Testing"
      - dependency-name: "NuGet.Protocol"
      - dependency-name: "NuGet.Packaging"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"